### ISSUE TITLE
Error: InsufficientRecommendationSpace in RL model evaluation step

### ISSUE THREAD

**Issue by Michal-Kolomanski** [cyfronet-fid/recommender-system#334]
Currently, RL training on production instance with the latest production data raises an InsufficientRecommendationSpace error. 
On the other hand, the same code enabled successful training on the beta instance. The scope of this issue is to investigate the reason behind this error and fix it. 

The error stack trace: 
```
2022-02-10 13:06:23 | recommender.engines.base.base_pipeline | INFO | Finished RLModelTrainingStep!
2022-02-10 13:06:23 | recommender.engines.base.base_pipeline | INFO | Started RLModelEvaluationStep...
Traceback (most recent call last):
  File "/home/michal/.local/share/virtualenvs/recommender-system-dfVHVYpy/bin/flask", line 8, in <module>
    sys.exit(main())
  File "/home/michal/.local/share/virtualenvs/recommender-system-dfVHVYpy/lib/python3.7/site-packages/flask/cli.py", line 967, in main
    cli.main(args=sys.argv[1:], prog_name="python -m flask" if as_module else None)
  File "/home/michal/.local/share/virtualenvs/recommender-system-dfVHVYpy/lib/python3.7/site-packages/flask/cli.py", line 586, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/home/michal/.local/share/virtualenvs/recommender-system-dfVHVYpy/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/michal/.local/share/virtualenvs/recommender-system-dfVHVYpy/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/michal/.local/share/virtualenvs/recommender-system-dfVHVYpy/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/michal/.local/share/virtualenvs/recommender-system-dfVHVYpy/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/michal/.local/share/virtualenvs/recommender-system-dfVHVYpy/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/michal/.local/share/virtualenvs/recommender-system-dfVHVYpy/lib/python3.7/site-packages/flask/cli.py", line 426, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/home/michal/.local/share/virtualenvs/recommender-system-dfVHVYpy/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/michal/Desktop/Cyfronet/Recommender/recommender-system/recommender/__init__.py", line 63, in tmp_train_command
    train_command(task)
  File "/home/michal/Desktop/Cyfronet/Recommender/recommender-system/recommender/commands/train.py", line 54, in train_command
    globals()[f"_{task}"]()
  File "/home/michal/Desktop/Cyfronet/Recommender/recommender-system/recommender/commands/train.py", line 49, in _all
    RLPipeline(RL_PIPELINE_CONFIG_V1)()
  File "/home/michal/Desktop/Cyfronet/Recommender/recommender-system/recommender/engines/base/base_pipeline.py", line 71, in __call__
    data, details = step(data)
  File "/home/michal/Desktop/Cyfronet/Recommender/recommender-system/recommender/engines/rl/training/model_evaluation_step/model_evaluation_step.py", line 131, in __call__
    rewards, simulation_duration = self._evaluate_reward(actor, sarses)
  File "/home/michal/Desktop/Cyfronet/Recommender/recommender-system/recommender/engines/rl/training/model_evaluation_step/model_evaluation_step.py", line 84, in _evaluate_reward
    service_ids = self._get_recommendation(actor, state)
  File "/home/michal/Desktop/Cyfronet/Recommender/recommender-system/recommender/engines/rl/training/model_evaluation_step/model_evaluation_step.py", line 124, in _get_recommendation
    chosen_services = self.service_selector(weights, mask)
  File "/home/michal/Desktop/Cyfronet/Recommender/recommender-system/recommender/engines/rl/ml_components/service_selector.py", line 62, in __call__
    raise InsufficientRecommendationSpace()
recommender.errors.InsufficientRecommendationSpace

```

**Comment by Michal-Kolomanski** [comment]
The reason behind the bug, situation:
A user made such a query that there are only 3 available services. The user got a recommendation panel with 3 recommendations. Everything to this point is ordinary but when for example one of those 3 recommended services gets deleted (or changed in some way, etc...) we are no longer able to reconstruct such a recommendation panel because we have only 2 services instead of 3. Our RL pipeline was not ready for such a situation and it terminated the training.
