### ISSUE TITLE
pymongo.errors.AutoReconnect: connection pool paused

### ISSUE THREAD

**Issue by Michal-Kolomanski** [cyfronet-fid/recommender-system#355]
When multiprocessing is enabled this error sometimes occurs. Versions of packages may be the reason. 

Traceback:
```
Traceback (most recent call last):
  File "/home/michal/.local/share/virtualenvs/recommender-system-dfVHVYpy/bin/flask", line 8, in <module>
    sys.exit(main())
  File "/home/michal/.local/share/virtualenvs/recommender-system-dfVHVYpy/lib/python3.7/site-packages/flask/cli.py", line 967, in main
    cli.main(args=sys.argv[1:], prog_name="python -m flask" if as_module else None)
  File "/home/michal/.local/share/virtualenvs/recommender-system-dfVHVYpy/lib/python3.7/site-packages/flask/cli.py", line 586, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/home/michal/.local/share/virtualenvs/recommender-system-dfVHVYpy/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/michal/.local/share/virtualenvs/recommender-system-dfVHVYpy/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/michal/.local/share/virtualenvs/recommender-system-dfVHVYpy/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/michal/.local/share/virtualenvs/recommender-system-dfVHVYpy/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/michal/.local/share/virtualenvs/recommender-system-dfVHVYpy/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/michal/.local/share/virtualenvs/recommender-system-dfVHVYpy/lib/python3.7/site-packages/flask/cli.py", line 426, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/home/michal/.local/share/virtualenvs/recommender-system-dfVHVYpy/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/michal/Desktop/Cyfronet/Recommender/recommender-system/recommender/__init__.py", line 65, in tmp_train_command
    train_command(task)
  File "/home/michal/Desktop/Cyfronet/Recommender/recommender-system/recommender/commands/train.py", line 53, in train_command
    globals()[f"_{task}"]()
  File "/home/michal/Desktop/Cyfronet/Recommender/recommender-system/recommender/commands/train.py", line 36, in _rl_v1
    RLPipeline(RL_PIPELINE_CONFIG_V1)()
  File "/home/michal/Desktop/Cyfronet/Recommender/recommender-system/recommender/engines/base/base_pipeline.py", line 71, in __call__
    data, details = step(data)
  File "/home/michal/Desktop/Cyfronet/Recommender/recommender-system/recommender/engines/rl/training/data_extraction_step/data_extraction_step.py", line 47, in __call__
    sarses = self._generate_sarses()
  File "/home/michal/Desktop/Cyfronet/Recommender/recommender-system/recommender/engines/rl/training/data_extraction_step/data_extraction_step.py", line 66, in _generate_sarses
    real_sarses = regenerate_sarses(multi_processing=True, verbose=True)
  File "/home/michal/Desktop/Cyfronet/Recommender/recommender-system/recommender/engines/rl/ml_components/sarses_generator.py", line 341, in regenerate_sarses
    verbose=verbose,
  File "/home/michal/Desktop/Cyfronet/Recommender/recommender-system/recommender/engines/rl/ml_components/sarses_generator.py", line 317, in generate_sarses
    pool.map(executor, recommendations)
  File "/home/michal/.local/share/virtualenvs/recommender-system-dfVHVYpy/lib/python3.7/site-packages/billiard/pool.py", line 1416, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/home/michal/.local/share/virtualenvs/recommender-system-dfVHVYpy/lib/python3.7/site-packages/billiard/pool.py", line 1791, in get
    raise self._value.exception
pymongo.errors.AutoReconnect: 127.0.0.1:27022: connection pool paused

```

**Comment by Michal-Kolomanski** [comment]
Related: https://jira.mongodb.org/browse/PYTHON-3029

**Comment by Michal-Kolomanski** [comment]
Downgrading pymongo to 3.12 should resolve problem
